# fly.toml app configuration file generated for pokersettle
app = "pokersettle"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/healthcheck"
    protocol = "http"
  # Free tier limits
  memory = 256
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "pokersettle_data"
  destination = "/data"
  capacity = 1
